"""State Handles"""
game_state = "GAME_STATE"
private_state = "PRIVATE_STATE"
public_state = "PUBLIC_STATE"

"""Game Observations"""
bank_development_card_count = "BANK_DEVELOPMENT_CARD_COUNT"
longest_road_length = "LONGEST_ROAD_LENGTH"
largest_army_size = "LARGEST_ARMY_SIZE"
turn_number = "TURN_NUMBER"
build_phase = "BUILD_PHASE"
build_phase_reversed = "BUILD_PHASE_REVERSED"
build_phase_placed_settlement = "BUILD_PHASE_PLACED_SETTLEMENT"
build_phase_placed_road = "BUILD_PHASE_PLACED_ROAD"
bought_development_card_count = "BOUGHT_DEVELOPMENT_CARD_COUNT"
played_development_card_count = "PLAYED_DEVELOPMENT_CARD_COUNT"
vertex_settlement = "VERTEX_SETTLEMENT"
vertex_city = "VERTEX_CITY"
vertex_open = "VERTEX_OPEN"
edge_open = "EDGE_OPEN"
tile_has_robber = "TILE_HAS_ROBBER"
tile_resource = "TILE_RESOURCE"
tile_roll_number = "TILE_ROLL_NUMBER"
bank_resources = "BANK_RESOURCES"
current_player_trade = "CURRENT_PLAYER_TRADE"
current_roll = "CURRENT_ROLL"
vertex_has_port = "VERTEX_HAS_PORT"

"""Public Observations"""
current_player = "CURRENT_PLAYER"
must_move_robber = "MUST_MOVE_ROBBER"
must_discard = "MUST_DISCARD"
victory_points = "VICTORY_POINTS"
resource_card_count = "RESOURCE_CARD_COUNT"
development_card_count = "DEVELOPMENT_CARD_COUNT"
settlement_count = "SETTLEMENT_COUNT"
city_count = "CITY_COUNT"
road_count = "ROAD_COUNT"
longest_road = "LONGEST_ROAD"
owns_longest_road = "OWNS_LONGEST_ROAD"
owns_largest_army = "OWNS_LARGEST_ARMY"
offering_trade = "OFFERING_TRADE"
accepted_trade = "ACCEPTED_TRADE"
declined_trade = "DECLINED_TRADE"
development_cards_played = "DEVELOPMENT_CARDS_PLAYED"
vertex_owned = "VERTEX_OWNED"
edge_owned = "EDGE_OWNED"
port_access = "PORT_ACCESS"

"""Private Observation"""
resource_type_count = "RESOURCES_CARD_COUNT"
development_type_count = "DEVELOPMENT_CARDS"
development_type_bought_count = "DEVELOPMENT_CARD_BOUGHT"

"""Actions"""
accept_player_trade = "ACCEPT_PLAYER_TRADE"
bank_trade = "BANK_TRADE"
buy_development_card = "BUY_DEVELOPMENT_CARD"
cancel_player_trade = "CANCEL_PLAYER_TRADE"
confirm_player_trade = "CONFIRM_PLAYER_TRADE"
decline_player_trade = "DECLINE_PLAYER_TRADE"
discard = "DISCARD"
end_turn = "END_TURN"
general_port_trade = "GENERAL_PORT_TRADE"
move_robber = "MOVE_ROBBER"
offer_player_trade = "OFFER_PLAYER_TRADE"
place_city = "PLACE_CITY"
place_road = "PLACE_ROAD"
place_settlement = "PLACE_SETTLEMENT"
play_knight = "PLAY_KNIGHT"
play_monopoly = "PLAY_MONOPOLY"
play_road_building = "PLAY_ROAD_BUILDING"
play_year_of_plenty = "PLAY_YEAR_OF_PLENTY"
resource_port_trade = "RESOURCE_PORT_TRADE"
rob_player = "ROB_PLAYER"
roll_dice = "ROLL_DICE"
no_action = "NO_ACTION"

"""Compact State"""
current_player_index = "CURRENT_PLAYER_INDEX"
must_move_robber_index = "MUST_MOVE_ROBBER_INDEX"
owns_largest_army_index = "OWNS_LARGEST_ARMY_INDEX"
owns_longest_road_index = "OWNS_LONGEST_ROAD_INDEX"
offering_trade_index = "OFFERING_TRADE_INDEX"
tile_has_robber_index = "TILE_HAS_ROBBER_INDEX"
current_roll_index = "CURRENT_ROLL_INDEX"
port_resource_index = "PORT_RESOURCE_INDEX"
tile_resource_index = "TILE_RESOURCE_INDEX"
tile_roll_number_index = "TILE_ROLL_NUMBER_INDEX"

settlement_indices = "SETTLEMENT_INDICES"
road_indices = "ROAD_INDICES"
city_indices = "CITY_INDICES"
